export const defaultCourseSearchRequest: CourseSearchRequest = {
  keyword: "",
  categoryId: [],
  level: null,
  minPrice: null,
  maxPrice: null,
  minAverageRating: null,
  maxAverageRating: null,
  isFree: null,
  hasQuiz: null,
  tagNames: [],
  page: 0,
  size: 9,
  sortBy: "RELEVANCE",
};
